### ISSUE TITLE
Movie bot issues with returning results. 405 error

### ISSUE THREAD

**Issue by satishvad** [dongido001/flask_chatbot#1]
Hello,

I have used the example you provided in the link [here](https://pusher.com/tutorials/chatbot-flask-dialogflow). But, I am not sure when the @app.route('/get_movie_detail', methods=['POST']) is called and moreover, I get a 405 error on local host. Where in the code is that route triggered.

Thank you

**Comment by dongido001** [comment]
The `@app.route('/get_movie_detail', methods=['POST'])` route is called when you ask the bot for details about a movie and It's called by Dialogflow. Here is the [code](https://github.com/dongido001/flask_chatbot/blob/master/index.py#L24).

Maybe Dialogflow is making a GET request instead of POST request. Be sure you set the webhook in Dialogflow to POST.

**Comment by satishvad** [comment]
Thank you for the response. So, when something is typed and we hit enter first the /send_message is called. And within this we call the detect intent, but when is the api call to the movie database made? On debugging I do see the text entered. I can also have "small talk" conversations with the bot. It fails only when I try to search for movie. How do I set Dialogflow to be a POST? I thought the default is POST?

**Comment by dongido001** [comment]
So, when you send a message, yes, it will detect the intent. Once the intent is to get a movie detail, Dialogflow will make a request to the '/get_movie_detail' route. Are you using Ngrok?  Try visiting http://localhost:4040 to see the full log.

Ah yeah, I just saw the default method on Dialogflow is POST.
![image](https://user-images.githubusercontent.com/18917158/43977222-5228a758-9cdb-11e8-991c-8d483ce117ca.png)

Can you also the full error message you are getting, maybe that will help.

**Comment by satishvad** [comment]
Here is the response

{
    "responseId": "82f4556f-17a1-4178-9a31-35455904885c",
    "queryResult": {
        "queryText": "black panther",
        "parameters": {
            "movie": "black panther"
        },
        "allRequiredParamsPresent": true,
        "fulfillmentMessages": [
            {
                "text": {
                    "text": [
                        ""
                    ]
                }
            }
        ],
        "intent": {
            "name": "projects/movie-bot-2106a/agent/intents/3280f6ab-6c70-4347-aead-95f989439b6f",
            "displayName": "movie"
        },
        "intentDetectionConfidence": 1,
        "languageCode": "en"
    },
    "originalDetectIntentRequest": {
        "payload": {}
    },
    "session": "projects/movie-bot-2106a/agent/sessions/unique"
}

**Comment by satishvad** [comment]
Also, how does Dialogflow know to call /get_movie route. Where are we telling dialogflow to do that? Sorry for all these novice questions.

**Comment by satishvad** [comment]
Oh! man. I missed the /get_movie_detail to be added to the fulfillment in the dialogflow. Sorry. I did that it is entering the route. But, now the error is with "movie_detail = json.loads(movie_detail)" line, the JSON object must be str, not 'bytes'

**Comment by dongido001** [comment]
I think this looks okay.

**How does Dialogflow know to call /get_movie route?**
For every message you submit, we detect the intent of that text. Now let's say you sent "Hello". The intent that will be detected on the "Hello" message is greeting(small talk). Now Dialogflow will respond with greeting, since we have configured small talk. But, if you sent a message like "I want details of Black Panther", the intent of the text will be detected as movie_intent. Now, Dialogflow will try to get details of the Black Panther movie. But Diaflogflow does not know about movies, that's why we added a webhook in the Diaflogflow console/dashboard. So for Dialogflow to get the details of the movie, it will simply make a request to the webhook we addded. 

From the image below, you will in the URL field, I add this - `https://b7497144.ngrok.io/get_movie_detail` which is my localhost which Ngrok exposed so Dialogflow can access it. The `get_movie_detail` in the URL matches the `@app.route('/get_movie_detail', methods=['POST'])` route.

**Comment by dongido001** [comment]
Oh right! You might have missed some configuration for the Movie API

**Comment by satishvad** [comment]
And finally I had to change the code to movie_detail = json.loads(movie_detail.decode("utf-8")) in the /get_movie_detail route and all is good now. Thank you so much for the tutorial and for helping me out.

**Comment by VenkatachalamVE** [comment]
Respected Sir/Madam,

                       In Dialogflow, While multiple user chatting at same time, there is some errors occurred while retrieving data, If First User enters value it retrieves correctly but the second user enters the value in the follow-up intent directly, that also gives response instead of fallback intent reponse.

Multiple User can access the chat or not (Accurate Response)?
                                                            Thanking You   
                                                                                                          Your's Respectfully
                                                                                                           Venkatachlam. VE

**Comment by VenkatachalamVE** [comment]
Kindly Reply Immediately.
