### ISSUE TITLE
"Unique" what does it exactly mean??

### ISSUE THREAD

**Issue by shreyasharma98** [dongido001/flask_chatbot#7]
I've gone through the tut on flask-dialogflow chatbot..
In the function ```send_message()``` u 've used ```fulfillment_text = detect_intent_texts(project_id, "unique", message, 'en')```
what does the ```"unique"``` meant here ?? Do we have to use the "unique" it self or it is a unique key or something..if yes then from where we'll find this......!!

bcz, I'm getting error at session not found for this!!

**Comment by shreyasharma98** [comment]
@dongido001
Plz look!!

**Comment by dongido001** [comment]
Hi...

The "unique" is actually some unique value for each user using the bot. Although in this case it's constant and does not change for all users, it's intentional as I just want to keep things simple for the tutorial. Here is more on this - https://cloud.google.com/dialogflow/docs/quick/api#detect_intent

This should actually not be a problem for you to get the project up and running.

> "bcz, I'm getting an error at a session not found for this!!"
 weird, ok. I am checking on this now to confirm....

**Comment by dongido001** [comment]
@shreyasharma98 it works just fine. Feel free to send me an email here: ********, maybe we can walk through your setup through Team Viewer or similar...

**Comment by dongido001** [comment]
@shreyasharma98 let me know how it went :)
